export interface LegacyCertificate {
  id: string;
  title: string;
  issuer: string;
  focus: string;
  image: string;
}

export const FEATURED_CERTIFICATES: LegacyCertificate[] = [
  {
    id: "infosec-cissp-specialization",
    title: "Certified Information Systems Security Professional (CISSP) Specialization",
    issuer: "InfoSec عبر Coursera",
    focus: "مسار مهني متقدم من 8 دورات يغطي نطاقات CISSP الثمانية ويهيئ لاختبار ISC2 CISSP، مع شهادة إتمام قابلة للتحقق من Coursera.",
    image: "/certificates/infosec-cissp-specialization.jpg",
  },
  {
    id: "cde-cybersecurity-professional-2025",
    title: "Cybersecurity Professional — Certificate of Achievement",
    issuer: "Cyber Defense Excellence (CDE)",
    focus: "شهادة إنجاز مهنية كما تظهر في الوثيقة المرفوعة، وتعرض محاور اختبار الاختراق وأمن الشبكات والويب وSIEM والاستجابة للحوادث.",
    image: "/certificates/cde-cybersecurity-professional-2025.jpg",
  },
  {
    id: "ibm-isc2-cybersecurity-specialist-master",
    title: "IBM and ISC2 Cybersecurity Specialist",
    issuer: "IBM وISC2 عبر Coursera",
    focus: "شهادة مهنية دولية من IBM وISC2 لمسار متكامل من 12 دورة، تبني أساسًا قويًا في الأمن السيبراني والشبكات والسحابة والاستجابة للحوادث والعمليات الأمنية، مع مشروع تطبيقي ختامي.",
    image: "/certificates/ibm-isc2-cybersecurity-specialist.jpg",
  },
  {
    id: "isc2-security-operations",
    title: "Security Operations",
    issuer: "ISC2 عبر Coursera",
    focus: "عمليات الأمن والمراقبة والاستجابة ضمن مسار CISSP",
    image: "/certificates/isc2-security-operations.jpg",
  },
  {
    id: "isc2-network-security",
    title: "Network Security",
    issuer: "ISC2 عبر Coursera",
    focus: "أمن الشبكات والاتصالات ضمن مسار CISSP",
    image: "/certificates/isc2-network-security.jpg",
  },
  {
    id: "isc2-incident-response-bc-dr",
    title: "Incident Response, BC, and DR Concepts",
    issuer: "ISC2 عبر Coursera",
    focus: "الاستجابة للحوادث واستمرارية الأعمال والتعافي من الكوارث",
    image: "/certificates/isc2-incident-response-bc-dr.jpg",
  },
  {
    id: "isc2-cissp-domain-7-security-operations",
    title: "CISSP Domain 7: Security Operations",
    issuer: "ISC2 عبر Coursera",
    focus: "العمليات الأمنية، المراقبة، الاستجابة للحوادث، والتعافي التشغيلي",
    image: "/certificates/isc2-cissp-security-operations.jpg",
  },
  {
    id: "isc2-access-control-concepts",
    title: "Access Control Concepts",
    issuer: "ISC2 عبر Coursera",
    focus: "التحكم بالوصول وإدارة الصلاحيات والهوية",
    image: "/certificates/isc2-access-control-concepts.jpg",
  },
  {
    id: "isc2-cissp-domain-4-network-security",
    title: "CISSP Domain 4: Communication and Network Security",
    issuer: "ISC2 عبر Coursera",
    focus: "الاتصالات وأمن الشبكات",
    image: "/certificates/isc2-cissp-network-security.jpg",
  },
  {
    id: "isc2-cissp-domain-8-software-security",
    title: "CISSP Domain 8: Software Development Security",
    issuer: "ISC2 عبر Coursera",
    focus: "أمن تطوير البرمجيات ودورة حياة التطوير الآمن",
    image: "/certificates/isc2-cissp-software-development-security.jpg",
  },
  {
    id: "isc2-security-principles",
    title: "Security Principles",
    issuer: "ISC2 عبر Coursera",
    focus: "مبادئ الأمن وإدارة المخاطر والضوابط الأساسية",
    image: "/certificates/isc2-security-principles.jpg",
  },
  {
    id: "isc2-cissp-domain-3-security-architecture",
    title: "CISSP Domain 3: Security Architecture",
    issuer: "ISC2 عبر Coursera",
    focus: "هندسة الأمن والتصميم الآمن للأنظمة",
    image: "/certificates/isc2-cissp-security-architecture.jpg",
  },
  {
    id: "isc2-cissp-domain-6-security-assessment",
    title: "CISSP Domain 6: Security Assessment and Testing",
    issuer: "ISC2 عبر Coursera",
    focus: "تقييم الأمن والاختبارات الأمنية وقياس فعالية الضوابط",
    image: "/certificates/isc2-cissp-security-assessment-testing.jpg",
  },
  {
    id: "cde-cybersecurity-professional",
    title: "Cybersecurity Professional — Certificate of Achievement",
    issuer: "Cyber Defense Excellence (CDE)",
    focus: "اختبار الاختراق، أمن الشبكات، أمن الويب، SIEM، والاستجابة للحوادث",
    image: "/certificates/cde-cybersecurity-professional.jpg",
  },
  {
    id: "ibm-isc2-cybersecurity-specialist",
    title: "IBM and ISC2 Cybersecurity Specialist",
    issuer: "IBM وISC2 عبر Coursera",
    focus: "تخصص شامل في الأمن السيبراني يضم مسارات IBM وISC2 العملية",
    image: "/certificates/ibm-isc2-cybersecurity-specialist.jpg",
  },
  {
    id: "ibm-cybersecurity-essentials",
    title: "Introduction to Cybersecurity Essentials",
    issuer: "IBM عبر Coursera",
    focus: "أساسيات الأمن السيبراني والمفاهيم العملية",
    image: "/certificates/ibm-cybersecurity-essentials.jpg",
  },
  {
    id: "ibm-cybersecurity-careers",
    title: "Introduction to Cybersecurity Careers",
    issuer: "IBM عبر Coursera",
    focus: "المسارات المهنية والمهارات الأساسية في الأمن السيبراني",
    image: "/certificates/ibm-cybersecurity-careers.jpg",
  },
  {
    id: "ibm-cybersecurity-storage",
    title: "Introduction to Networking and Storage",
    issuer: "IBM عبر Coursera",
    focus: "الشبكات والتخزين ومفاهيم البنية التحتية",
    image: "/certificates/ibm-cybersecurity-storage.jpg",
  },
  {
    id: "google-ai-app-building",
    title: "AI for App Building",
    issuer: "Google عبر Coursera",
    focus: "بناء التطبيقات باستخدام أدوات الذكاء الاصطناعي",
    image: "/certificates/google-ai-app-building.jpg",
  },
  {
    id: "hackviser-core-cybersecurity",
    title: "CORE — Certified Cybersecurity Foundations",
    issuer: "Hackviser",
    focus: "أساسيات الأمن السيبراني والتدريبات العملية",
    image: "/certificates/hackviser-core-cybersecurity.jpg",
  },
  {
    id: "google-network-security",
    title: "Connect and Protect: Networks and Network Security",
    issuer: "Google عبر Coursera",
    focus: "الشبكات وأمن الشبكات",
    image: "/certificates/google-network-security.jpg",
  },
  {
    id: "google-cybersecurity-jobs",
    title: "Put It to Work: Prepare for Cybersecurity Jobs",
    issuer: "Google عبر Coursera",
    focus: "الاستعداد للعمل في الأمن السيبراني",
    image: "/certificates/google-cybersecurity-jobs.jpg",
  },
  {
    id: "ibm-cybersecurity-capstone",
    title: "Cybersecurity Case Studies and Capstone Project",
    issuer: "IBM عبر Coursera",
    focus: "دراسات الحالة ومشروع التخرج في الأمن السيبراني",
    image: "/certificates/ibm-cybersecurity-capstone.jpg",
  },
  {
    id: "ibm-cloud-computing",
    title: "Introduction to Cloud Computing",
    issuer: "IBM عبر Coursera",
    focus: "مقدمة في الحوسبة السحابية",
    image: "/certificates/ibm-cloud-computing.jpg",
  },
  {
    id: "ibm-software-programming-databases",
    title: "Introduction to Software, Programming, and Databases",
    issuer: "IBM عبر Coursera",
    focus: "البرمجيات والبرمجة وقواعد البيانات",
    image: "/certificates/ibm-software-programming-databases.jpg",
  },
  {
    id: "ibm-hardware-operating-systems",
    title: "Introduction to Hardware and Operating Systems",
    issuer: "IBM عبر Coursera",
    focus: "العتاد وأنظمة التشغيل",
    image: "/certificates/ibm-hardware-operating-systems.jpg",
  },
  {
    id: "google-ai-professional",
    title: "Google AI Professional Certificate",
    issuer: "Google عبر Coursera",
    focus: "مسار احترافي من 7 دورات في الذكاء الاصطناعي وتطبيقاته العملية",
    image: "/certificates/google-ai-professional.jpg",
  },
  {
    id: "google-ai-fundamentals",
    title: "AI Fundamentals",
    issuer: "Google عبر Coursera",
    focus: "أساسيات الذكاء الاصطناعي",
    image: "/certificates/google-ai-fundamentals.jpg",
  },
  {
    id: "google-ai-content-creation",
    title: "AI for Content Creation",
    issuer: "Google عبر Coursera",
    focus: "استخدام الذكاء الاصطناعي في إنشاء المحتوى",
    image: "/certificates/google-ai-content-creation.jpg",
  },
  {
    id: "google-ai-research-insights",
    title: "AI for Research and Insights",
    issuer: "Google عبر Coursera",
    focus: "البحث واستخلاص الرؤى باستخدام الذكاء الاصطناعي",
    image: "/certificates/google-ai-research-insights.jpg",
  },
  {
    id: "google-ai-communication",
    title: "AI for Writing and Communicating",
    issuer: "Google عبر Coursera",
    focus: "الذكاء الاصطناعي والكتابة والتواصل المهني",
    image: "/certificates/google-ai-communication.jpg",
  },
  {
    id: "hackviser-csoa",
    title: "Certified Security Operations Analyst (CSOA)",
    issuer: "Hackviser",
    focus: "عمليات الأمن، اكتشاف التهديدات، والتحقيق الجنائي الرقمي عبر اختبار عملي",
    image: "/certificates/hackviser-csoa.jpg",
  },
  {
    id: "hackviser-capt",
    title: "Certified Associate Penetration Tester (CAPT)",
    issuer: "Hackviser",
    focus: "منهجيات وأدوات وتقنيات اختبار الاختراق عبر تقييم عملي",
    image: "/certificates/hackviser-capt.jpg",
  },
  {
    id: "hackviser-cwse",
    title: "Certified Web Security Expert (CWSE)",
    issuer: "Hackviser",
    focus: "أمن الويب وتقييم الثغرات والمنهجيات المتقدمة عبر اختبار عملي",
    image: "/certificates/hackviser-cwse.jpg",
  },
  {
    id: "cde-cybersecurity-achievement",
    title: "Cybersecurity Professional — Certificate of Achievement",
    issuer: "Cyber Defense Excellence (CDE)",
    focus: "اختبار الاختراق وأمن الشبكات وتطبيقات الويب والاستجابة للحوادث",
    image: "/certificates/cde-cybersecurity-achievement.jpg",
  },
  {
    id: "one-million-prompters",
    title: "1 Million Prompters — Certificate of Completion",
    issuer: "Dubai Future Foundation / Dubai Centre for Artificial Intelligence",
    focus: "هندسة الأوامر والذكاء الاصطناعي",
    image: "/certificates/one-million-prompters.jpg",
  },
  {
    id: "cisco-introduction-cybersecurity",
    title: "Introduction to Cybersecurity",
    issuer: "Cisco Networking Academy",
    focus: "مقدمة في الأمن السيبراني والتهديدات وحماية الأنظمة",
    image: "/certificates/cisco-introduction-cybersecurity.jpg",
  },
  {
    id: "opswat-icip",
    title: "Introduction to Critical Infrastructure Protection (ICIP)",
    issuer: "OPSWAT Academy",
    focus: "حماية البنية التحتية الحيوية",
    image: "/certificates/opswat-icip.jpg",
  },
  {
    id: "hackviser-csoa",
    title: "Certified Security Operations Analyst (CSOA)",
    issuer: "Hackviser",
    focus: "عمليات الأمن، اكتشاف التهديدات، والتحقيق الجنائي الرقمي عبر اختبار عملي",
    image: "/certificates/hackviser-csoa.jpg",
  },
  {
    id: "hackviser-capt",
    title: "Certified Associate Penetration Tester (CAPT)",
    issuer: "Hackviser",
    focus: "منهجيات وأدوات وتقنيات اختبار الاختراق عبر تقييم عملي",
    image: "/certificates/hackviser-capt.jpg",
  },
  {
    id: "hackviser-cwse",
    title: "Certified Web Security Expert (CWSE)",
    issuer: "Hackviser",
    focus: "أمن الويب وتقييم الثغرات والمنهجيات المتقدمة عبر اختبار عملي",
    image: "/certificates/hackviser-cwse.jpg",
  },
  {
    id: "cde-cybersecurity-achievement",
    title: "Cybersecurity Professional — Certificate of Achievement",
    issuer: "Cyber Defense Excellence (CDE)",
    focus: "اختبار الاختراق وأمن الشبكات وتطبيقات الويب والاستجابة للحوادث",
    image: "/certificates/cde-cybersecurity-achievement.jpg",
  },
  {
    id: "one-million-prompters",
    title: "1 Million Prompters — Certificate of Completion",
    issuer: "Dubai Future Foundation / Dubai Centre for Artificial Intelligence",
    focus: "هندسة الأوامر والذكاء الاصطناعي",
    image: "/certificates/one-million-prompters.jpg",
  },
  {
    id: "cisco-introduction-cybersecurity",
    title: "Introduction to Cybersecurity",
    issuer: "Cisco Networking Academy",
    focus: "مقدمة في الأمن السيبراني والتهديدات وحماية الأنظمة",
    image: "/certificates/cisco-introduction-cybersecurity.jpg",
  },
];
