/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as PortsIndexRouteImport } from './routes/ports.index'
import { Route as PortsPortIdRouteImport } from './routes/ports.$portId'
import { Route as VulnerabilitiesIndexRouteImport } from './routes/vulnerabilities.index'
import { Route as VulnerabilitiesVulnIdRouteImport } from './routes/vulnerabilities.$vulnId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsIndexRoute = PortsIndexRouteImport.update({
  id: '/ports/',
  path: '/ports/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsPortIdRoute = PortsPortIdRouteImport.update({
  id: '/ports/$portId',
  path: '/ports/$portId',
  getParentRoute: () => rootRouteImport,
} as any)
const VulnerabilitiesIndexRoute = VulnerabilitiesIndexRouteImport.update({
  id: '/vulnerabilities/',
  path: '/vulnerabilities/',
  getParentRoute: () => rootRouteImport,
} as any)
const VulnerabilitiesVulnIdRoute = VulnerabilitiesVulnIdRouteImport.update({
  id: '/vulnerabilities/$vulnId',
  path: '/vulnerabilities/$vulnId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/certificates': typeof CertificatesRoute
  '/tools': typeof ToolsRoute
  '/videos': typeof VideosRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/ports/$portId': typeof PortsPortIdRoute
  '/vulnerabilities/$vulnId': typeof VulnerabilitiesVulnIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/ports/': typeof PortsIndexRoute
  '/vulnerabilities/': typeof VulnerabilitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/certificates': typeof CertificatesRoute
  '/tools': typeof ToolsRoute
  '/videos': typeof VideosRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/ports/$portId': typeof PortsPortIdRoute
  '/vulnerabilities/$vulnId': typeof VulnerabilitiesVulnIdRoute
  '/courses': typeof CoursesIndexRoute
  '/ports': typeof PortsIndexRoute
  '/vulnerabilities': typeof VulnerabilitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/certificates': typeof CertificatesRoute
  '/tools': typeof ToolsRoute
  '/videos': typeof VideosRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/ports/$portId': typeof PortsPortIdRoute
  '/vulnerabilities/$vulnId': typeof VulnerabilitiesVulnIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/ports/': typeof PortsIndexRoute
  '/vulnerabilities/': typeof VulnerabilitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/certificates'
    | '/tools'
    | '/videos'
    | '/courses/$courseId'
    | '/ports/$portId'
    | '/vulnerabilities/$vulnId'
    | '/courses/'
    | '/ports/'
    | '/vulnerabilities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/certificates'
    | '/tools'
    | '/videos'
    | '/courses/$courseId'
    | '/ports/$portId'
    | '/vulnerabilities/$vulnId'
    | '/courses'
    | '/ports'
    | '/vulnerabilities'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/certificates'
    | '/tools'
    | '/videos'
    | '/courses/$courseId'
    | '/ports/$portId'
    | '/vulnerabilities/$vulnId'
    | '/courses/'
    | '/ports/'
    | '/vulnerabilities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRoute
  CertificatesRoute: typeof CertificatesRoute
  ToolsRoute: typeof ToolsRoute
  VideosRoute: typeof VideosRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  PortsPortIdRoute: typeof PortsPortIdRoute
  VulnerabilitiesVulnIdRoute: typeof VulnerabilitiesVulnIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  PortsIndexRoute: typeof PortsIndexRoute
  VulnerabilitiesIndexRoute: typeof VulnerabilitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports/': {
      id: '/ports/'
      path: '/ports'
      fullPath: '/ports/'
      preLoaderRoute: typeof PortsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports/$portId': {
      id: '/ports/$portId'
      path: '/ports/$portId'
      fullPath: '/ports/$portId'
      preLoaderRoute: typeof PortsPortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vulnerabilities/': {
      id: '/vulnerabilities/'
      path: '/vulnerabilities'
      fullPath: '/vulnerabilities/'
      preLoaderRoute: typeof VulnerabilitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vulnerabilities/$vulnId': {
      id: '/vulnerabilities/$vulnId'
      path: '/vulnerabilities/$vulnId'
      fullPath: '/vulnerabilities/$vulnId'
      preLoaderRoute: typeof VulnerabilitiesVulnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRoute,
  CertificatesRoute: CertificatesRoute,
  ToolsRoute: ToolsRoute,
  VideosRoute: VideosRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  PortsPortIdRoute: PortsPortIdRoute,
  VulnerabilitiesVulnIdRoute: VulnerabilitiesVulnIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  PortsIndexRoute: PortsIndexRoute,
  VulnerabilitiesIndexRoute: VulnerabilitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
